# Generated by Django 2.2.6 on 2020-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20191107_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
