# Generated by Django 2.2.6 on 2019-11-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('milk', 'молоко'), ('cheese', 'сыр'), ('sour_creame', 'сметана')], default='milk', max_length=20)),
                ('status', models.CharField(choices=[('available', 'есть в наличии'), ('unavailable', 'нет в наличии'), ('available_soon', 'скоро будет в наличии')], default='available', max_length=50)),
                ('unit_type', models.CharField(choices=[('liter', 'литр'), ('piece', 'штука'), ('kilogramm', 'килограмм')], default='piece', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='product.Product')),
            ],
        ),
    ]
