# Generated by Django 2.2.6 on 2020-01-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_image',
            new_name='image',
        ),
    ]
